// Auto generated by apis tool!
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable prefer-rest-params */
import { Model } from 'egg/speech';
import { rpc } from '../rpc';
export const project = {
  /**
   * load
   */
  load(): Promise<config.Project> {
    return rpc.request('project.load', ...arguments);
  },
  /**
   * save
   */
  save(cfg: config.Project): Promise<void> {
    return rpc.request('project.save', ...arguments);
  },
};

export const speech = {
  /**
   * get models list
   */
  models(): Promise<Array<Model>> {
    return rpc.request('speech.models', ...arguments);
  },
  /**
   * save meta data
   */
  saveTransferMeta(name: string, data: any): Promise<void> {
    return rpc.request('speech.saveTransferMeta', ...arguments);
  },
};

export const fs = {
  /**
   * readFile
   */
  readFile(filepath: string): Promise<Buffer> {
    return rpc.request('fs.readFile', ...arguments);
  },
  /**
   * writeFile
   */
  writeFile(filepath: string, data: Buffer): Promise<void> {
    return rpc.request('fs.writeFile', ...arguments);
  },
};
